### PR TITLE
Show description in ICS

### PR DESCRIPTION
**Pull request by kprkpr**
Hi, this is a PR about issue #1, with that has a variable (const SHOW_DESCR = true) to show or not description, and it shows the non-html version (I didn't know how to access "X-ALT-DESC;FMTTYPE=text/html" in $event, and it's easier to use DESCRIPTION argument and add newlines and preg_replace to links
For me worked for teams invitations but I had a problem, href links shows as a button and in inspector says class="button", can be this disabled¿? Don't know why is adding it..
image

### CODE REVIEW

**Comment by pulsejet** [comment]
This needs to:
* Use config files
* Look better on elastic

I'll fix the two above. Are you sure that regex is foolproof?

**Comment by kprkpr** [comment]
I didn't knew about config files, that's why I did as a variable.. If you say me how, I can try to do it
About look better.... In elastic, only problem too seems to be the links..
image
About foolproof, I changed regex, will commit one with regex for http(s) links and mailto: emails, complies with amazon meetings and microsoft teams meetings..

**Comment by pulsejet** [comment]
> I didn't knew about config files, that's why I did as a variable.. If you say me how, I can try to do it

I'll fix that don't worry about it. Also some CSS should fix the links.

> About foolproof, I changed regex, will commit one with regex for http(s) links and mailto: emails, complies with amazon meetings and microsoft teams meetings..

Hmm .. I don't want to introduce potential XSS. Maybe we should just use `rcube_text2html`

**Comment by kprkpr** [comment]
Yea... The regex I put it's only for converting <link.com> to <a href="link.com">link.com</a> and finds real links, but I'm not a pro of XSS prevention.. I changed integration to rcube_text2html. I had to delete the <, > and mailto: prefixes of links, but it works in teams and meets as before

**Comment by pulsejet** [comment]
Nice. I'll probably tweak this a bit.

**Comment by pulsejet** [comment]
This looks fair to me now. Set `banner_ics_description` in `config.inc.php` to turn on showing the description.

**Comment by kprkpr** [comment]
Tested and working okay
The mailto: didn't show very well, but more than acceptable, at least for me
image
Thanks :)

**Comment by pulsejet** [comment]
I doubt this is something that can be fixed consistently. The text may also read something like
```
Hello World<mailto:hello@world.net>
```
in which case the best we can do is remove the `mailto`. Don't see a lot of advantage here, but if this is something standardized, maybe open a separate issue/PR.

**Pull request merged**
